# Generated by Django 4.1.3 on 2023-01-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_main', '0008_caregory_name_ru_caregory_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='caregory',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subject_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subject_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_uz',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='name_uz',
        ),
    ]
