# Generated by Django 4.1.3 on 2023-01-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabrics_main', '0009_remove_caregory_name_ru_remove_caregory_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregory',
            name='name_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='caregory',
            name='name_uz',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_uz',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Maxsulot nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Maxsulot nomi'),
        ),
        migrations.AddField(
            model_name='product',
            name='subject_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subject_uz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlovha'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlovha'),
        ),
    ]
